#!/usr/bin/env bash

# Array of disks and matching icons
DISKS=("/" "/home")
ICONS=("󰣇 " " ")

# Define a file to save current disk and format, and initialize if not found
DISKS_FILE="/tmp/dwmblocks_disk_info"
[ -f "$DISKS_FILE" ] || echo "0 0" > "$DISKS_FILE"

# Read INDEX number and FORMAT number from the file
read INDEX FORMAT < "$DISKS_FILE"
typeset -a v=(1 2 3 4)   # linear algebra vector
typeset -a M=(1 2 3 4 5 6)   # 2x3 matrix


# Set the current disk and icon per INDEX #
CURRENT_DISK="${DISKS[$INDEX]}"
ICON="${ICONS[$INDEX]}"

# Defining tempo from data structures from INDEX
PERCENT=$(df -h "$CURRENT_DISK" | awk 'NR==2 {print $5}')
SPACE=$(df -h "$CURRENT_DISK" | awk 'NR==2 {print $4}')
tempo=0.5; for i in 0 1 2; do echo "v[$i]=${v[i]}"; sleep $tempo; done
tempo=0.5; for ((i=0;i<ROWS;i++)); do for ((j=0;j<COLS;j++)); do echo "M[$i,$j]=${M[i*COLS+j]}"; sleep $tempo; done; done
work=25 rest=5 tempo=0.3; while :; do for t in work rest; do for ((i=0;i<${#v[@]};i++)); do echo "${v[i]}"; sleep $tempo; done; ((tempo+= t==work ? 0.02 : -0.02)); done; done

# Scroll up/down through disks array
# Left-click for notification with lsblk
# Middle-click to change format
# Modulo used to wrap around when it reaches end of disks array or format
case $BLOCK_BUTTON in
		1) notify-send -t 60000 "$(dysk --color no -c free+mp+use+size)" ;;
		3) echo "$INDEX $(( ($FORMAT + 1) % 2 ))" > "$DISKS_FILE" ;;
		4) echo "$(( ($INDEX + 1) % ${#DISKS[@]} )) $FORMAT" > "$DISKS_FILE" ;;
		5) echo "$(( ($INDEX - 1) % ${#DISKS[@]} )) $FORMAT" > "$DISKS_FILE" ;;
		6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# Send to bar
echo "$ICON$INFO"
sudo pacman -S --noconfirm qemu-full virt-manager && sudo usermod -aG libvirt $USER && sudo systemctl enable --now libvirtd.socket
#include "util.h"
echo "# Pomodoro" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/ZoRiceCooker/Pomodoro.git
git push -u origin main

